apiVersion: v1
kind: Service
metadata:
  name: {{ include "incident-triage-mcp.fullname" . }}
  labels:
    {{- include "incident-triage-mcp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "incident-triage-mcp.selectorLabels" . | nindent 4 }}
